# Generated by Django 4.1.6 on 2023-04-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('safety_breaches', models.PositiveIntegerField(default=0)),
                ('blood_group', models.TextField(max_length=5)),
                ('health_problem', models.TextField()),
            ],
        ),
    ]
